version: "3.7"

services:
  petshop-db:
    image: sixeyed/petshop-db:1809
    build:
      context: ..
      dockerfile: docker/db/Dockerfile

  petshop-web:
    image: sixeyed/petshop-web:1809
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
      target: v4      

  petshop-web-v41:
    image: sixeyed/petshop-web:v4.1-1809
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
      target: v41

  petshop-webservice:
    image: sixeyed/petshop-webservice:1809
    build:
      context: ..
      dockerfile: docker/webservice/Dockerfile
