version: "3.3"

services:
  petshop-db:
    image: sixeyed/petshop-db:1809
    build:
      context: ..
      dockerfile: docker/db/Dockerfile

  petshop-web:
    image: sixeyed/petshop-web:1809
    build:
      context: ..
      dockerfile: docker/web/Dockerfile

  petshop-webservice:
    image: sixeyed/petshop-webservice:1809
    build:
      context: ..
      dockerfile: docker/webservice/Dockerfile
